name = "responses-api-demo"
main = "worker/index.ts"
compatibility_date = "2024-01-01"

# Worker configuration
[build]
command = "npm run build"

# Environment variables (non-sensitive)
[vars]
# Sensitive variables like OPENAI_API_KEY should be in .dev.vars for local development
# and set as secrets in production using: wrangler secret put OPENAI_API_KEY
